DROP USER scrum CASCADE

CREATE USER scrum IDENTIFIED BY scrum DEFAULT TABLESPACE CRDSDAT01 TEMPORARY TABLESPACE temp;
ALTER USER scrum QUOTA UNLIMITED ON CRDSDAT01;
ALTER USER scrum QUOTA UNLIMITED ON CRDSIND01;

-- privileges
GRANT CONNECT TO scrum;
GRANT CREATE SESSION TO scrum;
GRANT CREATE PUBLIC SYNONYM TO scrum;
GRANT CREATE SYNONYM TO scrum;
GRANT DROP PUBLIC SYNONYM TO scrum;
GRANT DROP ANY SYNONYM TO scrum;
GRANT CREATE PROCEDURE, CREATE TRIGGER TO scrum;
GRANT CREATE ANY TABLE, CREATE SEQUENCE TO scrum;
GRANT DELETE ANY TABLE TO scrum;
GRANT CREATE ROLE TO scrum;
GRANT DEBUG CONNECT SESSION TO scrum;
GRANT CREATE TYPE TO scrum;
GRANT CREATE VIEW TO scrum;
GRANT EXECUTE ON SYS.DBMS_AQ TO scrum;
GRANT EXECUTE ON SYS.DBMS_AQADM TO scrum;
GRANT EXECUTE ON SYS.DBMS_PIPE TO scrum;
GRANT CREATE USER TO scrum WITH ADMIN OPTION;
GRANT ALTER USER TO scrum WITH ADMIN OPTION; 
GRANT CREATE SESSION TO scrum WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO scrum WITH ADMIN OPTION;
GRANT DROP USER TO scrum WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO scrum;
GRANT RESOURCE TO scrum;
GRANT ROLE_DBA TO scrum; 
GRANT DEBUG ANY PROCEDURE, DEBUG CONNECT SESSION TO scrum; 
GRANT EXECUTE ON SYS.UTL_MAIL TO scrum;
