// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.scrumtool.domain;

import com.scrumtool.domain.Location;

privileged aspect PublicHoliday_Roo_JavaBean {
    
    public Location PublicHoliday.getLocation() {
        return this.location;
    }
    
    public void PublicHoliday.setLocation(Location location) {
        this.location = location;
    }
    
}
